### ISSUE TITLE
New context command: Extempore Effects for...

### ISSUE THREAD

**Issue by apoapostolov** [itamarcu/pf2e-extempore-effects#1]
First let me thank you for this extremely useful mod, it helps a lot with cases where remembering custom spells and effects can be hard, and making a basic effect from a post is so much easier. 

I have a small request to make, that will help with custom durations needed on some posts that lack a duration. New command next to the existing one "Extempore Effects for..." causes a dialog to show where the GM can set duration in rounds, minutes, hours, days. This is useful for rare cases where the effect will need a custom duration and it can only be changed if you edit the effect once generated.

**Comment by itamarcu** [comment]
Yeah, that sounds like a good idea.  Though, instead of a new context command, I'll make it happen when Shift+Clicking the existing one.  It already opens up a dialog but it only allows renaming the effect at the moment.

**Comment by apoapostolov** [comment]
That works too, I'm only afraid that people aren't used to keybindings on
context menus and most people will never find it.

**Comment by itamarcu** [comment]
I decided to change this behavior (in v1.1.0) so that holding Shift will simply open the sheet for editing after it's applied.  This is simpler and more generic, allowing the user to edit any aspect of the effect.  Only two problems remain:

1. Editing an effect that you want to apply to multiple creatures is difficult!  But it can be solved by the user applying the effect to one token, editing it, then dragging from that token to other tokens.
2. Discoverability of the feature, as you've mentioned.  I'm not sure how to solve this, but for now I'm adding documentation about the feature in the readme.

For discoverability, I could take some more steps but they might annoy users:
a. Show a UI notification when a user applies an effect, saying that the effect was applied but also that they can hold Shift next time to edit it.  Maybe will no longer show after you use it with Shift once.
b. Add a settings menu option to change the default behavior (do or do not open sheet after applying)
c. Add an extra content option - I don't like this, because there's already a LOT of context menu options and I don't want to contribute to the problem:
![image](https://user-images.githubusercontent.com/6516621/175524854-ac0ace08-8064-4bfc-8b05-dca20add6929.png)

If you got another idea or a preference within those, let me know!

**Comment by itamarcu** [comment]
Another option, btw, is make that sheet open by default and have Shift prevent it from opening!
