### ISSUE TITLE
Feature Request: Keybinding to create dummy effect and open its dialog

### ISSUE THREAD

**Issue by apoapostolov** [itamarcu/pf2e-extempore-effects#4]
Keybinding such as SHIFT-E to create a new effect on one selected token and open its dialog immediately so the GM can edit its name and duration. A default icon that could appeal to all such quick conditions could be added to Settings so each GM can se their own. 

This solves a problem GM had when they need to create very quickly a new effect with a custom name and duration. An example of such usage is quickly creating Immunity to monster attacks for players who succeed in the save.

**Comment by itamarcu** [comment]
I can add this, but why not just use the existing Extempore Effect with shift-clicking to open the sheet?  That way an effect is immediately created and the user can immediately edit its name, icon, duration, etc - with the default system UI.

It seems to me that the only major difference with making it a keybinding is that the new effect's initial data (name, icon, duration, description) will be blank or have some default value, instead of depending on the chat message.  Is that a big enough difference for you?

**Comment by itamarcu** [comment]
Added in v1.2.0 (Ctrl+Shift+E but you can configure it), I hope this is helpful to you!

I made the icon random, but consistent as long as you don't pan or zoom;  this means that you can give the same icon to multiple player tokens a bit more easily.
